---
title: "Event agenda"
format:
  html:
    toc: true
    toc-expand: 2
---

# Workshop Format and Structure

The workshop is proposed as a **nine-day virtual event**, combining synchronous and asynchronous activities, to balance live interaction with flexibility for participants.

-   **Synchronous sessions** are proposed from **14:00 to 16:00 (Jakarta time, GMT+7)**. These sessions would focus on conceptual discussions, methodological guidance, live demonstrations, and interactive exchanges with the Task Team.

-   **Asynchronous activities** allow participants to engage with selected materials, exercises, or practical tasks at their own pace. These activities would build on the content of the synchronous sessions and reinforce key concepts and tools.

# Day by day agenda

## Monday September 21

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|----------------------------------|---------------------|
| 14:00 – 14:20 | Introduction to the workshop and round table | Tanya Flower / Helen Sands (UNTT, UK ONS), Indonesia Hub |
| 14:20 – 15:10 | Overview of alternative data sources for CPI compilation | Federico Polidoro (UNTT, World Bank) |
| 15:10 – 16:00 | Overview of the main challenges to obtain alternative data for CPI compilation | Federico Polidoro (UNTT, World Bank) |

## Tuesday September 22

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|----------------------------------|---------------------|
| 14:00 – 15:00 | Alternative data preparation, cleaning, and classification for price statistics | TBC – Serge Goussev / Federico Polidoro |

Asynchronous Activities (self paced).

The [pre-requisites page](/content/pre-reqs.qmd) outlines how you could stand coding without too much difficulty.

## Wednesday September 23

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|----------------------------------|---------------------|
| 14:00 – 15:00 | Q&A session for asynchronous activities | TBC – Caspien, Tanya, Federico |

Asynchronous Activities (self paced).

## Thursday September 24

Asynchronous Activities (self paced).

## Monday September 28

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|----------------------------------|---------------------|
| 14:00 – 15:00 | Use of alternative data sources in CPI compilation | Helen Sands (UNTT, UK ONS) |
| 15:00 – 16:00 | Quality assurance, validation, and comparison with traditional price data | Tanya Flower (UNTT, UK ONS) |

## Tuesday September 29

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|----------------------------------|---------------------|
| 14:00 – 15:00 | Introduction to tools and packages for multilateral indices using scanner data | Luigi Palumbo (UNTT, Bank of Italy), Oskar Eugster (UNTT, Statistics Switzerland) |

Asynchronous Activities (self paced). Check out the [Index calculation exercises in R](/notebooks/Index_Calculation_Exercises_in_R.ipynb) and ([solutions](/notebooks/Index_Calculation_Exercises_Solutions_in_R.ipynb)) and the same in [Python](/notebooks/index_calculation_exercises_Python.ipynb) (and [solutions](/notebooks/index_calculation_exercises_solutions_Python.ipynb))

## Wednesday September 30

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|----------------------------------|---------------------|
| 14:00 – 15:00 | Q&A session for asynchronous activities | Luigi Palumbo, Oskar Eugster, Tanya Flower, Federico Polidoro |

Asynchronous Activities (self paced).

## Thursday October 1

Asynchronous Activities (self paced).

## Friday October 2

| Time | **Session** | **Speakers / Facilitator** |
|-----------------|-----------------------|--------------------------------|
| 14:00 – 15:00 | Institutional and operational considerations for integrating scanner data into regular statistical production | Helen Sands (UNTT, UK ONS) |
| 15:00 – 15:45 | Conclusion, final Q&A, and way forward | Tanya Flower (UNTT, UK ONS), all presenters, Indonesia Hub |